Repository effector/patronum, pull requests merged in 2020-06, with the labels that each got.

#9 RFC: combineEvents (implementation, types, tests, no docs)
  combineEvents/combine-events.test.js
  combineEvents/index.d.ts
  combineEvents/index.js
Labels: enhancement

#15 Better cleanup for combineEvents
  combine-events/index.js
Labels: enhancement

#17 feat(condition): add ability to write nested conditions
  condition/condition.test.js
  condition/index.d.ts
  condition/index.js
Labels: enhancement

#18 add every
  .eslintrc.json
  .github/workflows/nodejs.yml
  README.md
  delay/delay.test.js
  every/every.test.js
  every/index.d.ts
  every/index.js
  every/readme.md
  index.d.ts
  index.js
  jest.config.js
  package.json
  test-d/every.ts
  yarn.lock
Labels: enhancement

#20 Add new method `some`
  README.md
  index.d.ts
  index.js
  some/index.d.ts
  some/index.js
  some/readme.md
  some/some.test.js
  test-d/some.ts
Labels: feature

#26 `splitMap` and `reshape` marked as ready to use
  README.md
Labels: documentation

#31 `throttle` method refactored, now supports only with object form
  .eslintrc.json
  .github/release-drafter.yml
  README.md
  library.js
  library.test.js
  package.json
  throttle/index.d.ts
  throttle/index.js
  throttle/readme.md
  throttle/throttle.fork.test.ts
  throttle/throttle.test.ts
  yarn.lock
Labels: BREAKING CHANGES

#36 Cover `throttle` with type tests
  .eslintrc.json
  test-d/throttle.ts
Labels: tests

#39 Split CI to different steps
  .github/workflows/nodejs.yml
  package.json
Labels: tests

#38 Fully refactored `debounce` method (object form arguments, pass latest value, supports target)
  debounce/debounce.fork.test.ts
  debounce/debounce.test.ts
  debounce/index.d.ts
  debounce/index.js
  debounce/readme.md
  package.json
  test-d/debounce.ts
  test-library.d.ts
  test-library.js
  throttle/index.js
  yarn.lock
Labels: BREAKING CHANGES

#41 Refactored `splitMap` to object form arguments
  .eslintrc.json
  README.md
  split-map/index.d.ts
  split-map/index.js
  split-map/readme.md
  split-map/split-map.fork.test.ts
  split-map/split-map.test.ts
  test-d/split-map.ts
Labels: BREAKING CHANGES

#43 Refactored `some` method (object form arguments)
  some/index.d.ts
  some/index.js
  some/readme.md
  some/some.fork.test.ts
  some/some.test.ts
  test-d/some.ts
Labels: BREAKING CHANGES

#50 Add object arguments form for `every` method
  README.md
  every/every.fork.test.ts
  every/every.test.js
  every/index.d.ts
  every/index.js
  every/readme.md
  test-d/every.ts
Labels: BREAKING CHANGES

#51 Implement object arguments form for `delay` method
  README.md
  delay/delay.fork.test.ts
  delay/delay.test.ts
  delay/index.d.ts
  delay/index.js
  delay/readme.md
  test-d/delay.ts
Labels: BREAKING CHANGES

#52 Fix broken types in `status` method
  status/index.d.ts
Labels: fix

#54 Fix types in `status` method
  status/index.d.ts
Labels: fix

#55 Add object arguments form for `status`
  README.md
  status/index.d.ts
  status/index.js
  status/readme.md
  status/status.test.js
Labels: BREAKING CHANGES

#56 Read arguments for `condition` using `readConfig`
  condition/index.js
Labels: feature

#57 Add object arguments form for `reshape` method
  README.md
  reshape/index.d.ts
  reshape/index.js
  reshape/readme.md
  reshape/reshape.test.js
Labels: BREAKING CHANGES

#58 Add object arguments form for `combineEvents`
  README.md
  combine-events/combine-events.test.js
  combine-events/index.d.ts
  combine-events/index.js
  combine-events/readme.md
Labels: BREAKING CHANGES

#61 Add object arguments form for `spread` method
  README.md
  spread/index.d.ts
  spread/index.js
  spread/readme.md
  spread/spread.test.js
Labels: BREAKING CHANGES

#63 Add `reset` and `target` options to `combine-events`
  combine-events/combine-events.test.js
  combine-events/combine-events.test.ts
  combine-events/index.d.ts
  combine-events/index.js
Labels: enhancement

#65 Enhanced types for `combineEvents`
  combine-events/combine-events.test.ts
  combine-events/index.d.ts
Labels: enhancement

#62 Add migration guide `v0.14` → `v0.100`
  MIGRATION.md
  README.md
Labels: documentation
