Repository effector/patronum, pull requests merged in 2022-08, with the labels that each got.

#220 Introduce `empty` operator
  src/babel-plugin-factories.json
  src/empty/empty.fork.test.ts
  src/empty/empty.test.ts
  src/empty/index.ts
  src/empty/readme.md
Labels: feature

#218 Add type tests for `format`
  test-typings/format.ts
Labels: tests

#225 fix `interval`'s `tick` logic
  src/interval/index.ts
  src/interval/interval.fork.test.ts
Labels: fix

#229 Fix `combineEvents` serialization
  src/combine-events/combine-events.fork.test.ts
  src/combine-events/index.ts
Labels: fix

#232 Fix `and` `or` state should be boolean
  src/and/and.fork.test.ts
  src/and/index.ts
  src/or/index.ts
  src/or/or.fork.test.ts
Labels: fix

#230 Fix naming in "Alternative" section similar to "Example"
  src/and/readme.md
Labels: documentation
