Repository effector/patronum, pull requests merged in 2023-03, with the labels that each got.

#276 Do not infer time param and add type tests for `time` operator
  src/time/index.ts
  src/time/time.fork.test.ts
  test-typings/time.ts
Labels: fix

#278 Allow `clock` in `snapshot` to be a Store or Effect and do not infer return value
  src/snapshot/index.ts
  src/snapshot/readme.md
  src/snapshot/snapshot.fork.test.ts
  src/snapshot/snapshot.test.ts
  test-typings/snapshot.ts
Labels: enhancement

#279 Allow to pass void to `delay`
  src/delay/index.ts
  test-typings/delay.ts
Labels: fix

#280 Allow `void` as `target` in `debounce` operator
  src/debounce/debounce.test.ts
  src/debounce/index.ts
  test-typings/debounce.ts
Labels: feature
